### ISSUE TITLE
Mustache tags inside HTML attributes not recognized

### ISSUE THREAD

**Issue by cperryk** [atom/language-mustache#10]
In the below example, the `{{test}}` tag is not recognized as mustache.

``` mustache
<a href="{{test}}"></a>
```

Here's a [screen](https://www.dropbox.com/s/ijhw3ohq9xlijzg/Screenshot%202015-06-05%2011.22.46.png?dl=0) of the example with the source HTML open.

**Comment by 50Wliu** [comment]
I'm pretty sure this is because the grammar includes the HTML grammar, which doesn't give Mustache a chance to match anything in attributes.  Not sure how to tackle this.

**Comment by 50Wliu** [comment]
The answer: injections!  Might restructure this whole grammar to use injections if/when I have the chance.
