### ISSUE TITLE
Mustache tags in style-tag breaks highlighting for the whole document.

### ISSUE THREAD

**Issue by Eschon** [atom/language-mustache#11]
Here is a little screenshot showing my issue:

![screen shot 2015-06-16 at 11 50 24](https://cloud.githubusercontent.com/assets/11647830/8180428/f22efbc0-141d-11e5-9439-69ceaebe06cd.png)

**Comment by 50Wliu** [comment]
I'm pretty sure the cause behind this is extremely similar to https://github.com/atom/language-mustache/issues/10#issuecomment-180183167, except that there's one extra level of nesting - `language-mustache` shells out to `language-html` which in turn gives control to `language-css` once it reaches a style tag.  CSS has the highest priority there, so it's probably matching the brackets before language-mustache can.
