### ISSUE TITLE
Please add JSON Grammar

### ISSUE THREAD

**Issue by qoomon** [atom/language-mustache#14]
Please add JSON Grammar

**Comment by mnquintana** [comment]
Can you be more specific? Are you looking for Mustache support within a JSON file?

**Comment by qoomon** [comment]
exactly

**Comment by 50Wliu** [comment]
As far as I'm aware (through a few minutes of searching Google), JSON does not support Mustache templates.  @qoomon please correct me if I'm wrong!  It would be really helpful as well if you could share some links or even a JSON file that has Mustache templates in it.
