### ISSUE TITLE
Create grammar that applies Mustache to another file extension (.tpl)

### ISSUE THREAD

**Issue by caleb531** [atom/language-mustache#26]
Hi,

I am writing an Atom package, and I want to apply this package's `HTML (Mustache)` grammar to another file extension (`.tpl` in this case), which is not currently supported by `mustache.cson`. Here is my current (custom) grammar:

```cson
'name': 'Foo Template'
'scopeName': 'text.html.foo.tpl'
'fileTypes': [
  'tpl'
]
'patterns': [
  {
    'include': 'text.html.mustache'
  }
]
```

The above only brings me halfway—HTML is tokenized/highlighted, but not the Mustache/Handlebars tags:

![screen shot 2017-09-19 at 3 07 09 pm](https://user-images.githubusercontent.com/872474/30617796-8ee22316-9d4c-11e7-9c1d-6a4d46381957.png)

I suspect there is a problem with my grammar, because if I directly set the language of my file to `HTML (Mustache)`, everything is highlighted. 

![screen shot 2017-09-19 at 3 07 21 pm](https://user-images.githubusercontent.com/872474/30617835-ba600c9c-9d4c-11e7-92cb-5445fd1ab8a8.png)

What am I missing or doing incorrectly?
Thanks,
Caleb

(Atom 1.20.1, macOS 10.12.6)

**Comment by 50Wliu** [comment]
All including `text.html.mustache` does is in turn include `text.html.basic`: https://github.com/atom/language-mustache/blob/cc02f37f85f54b7106aaf3d182e1f8f1751ab1cc/grammars/mustache.cson#L35.  In order to get Mustache highlighting to work I believe you need to add the `text.html.mustache` scope for the injections.  Perhaps it can target `text.html.basic` instead.  I'll have to see.

**Comment by caleb531** [comment]
@50Wliu I'm trying this, but it doesn't work either. Is there anything obviously wrong with the format?

```cson
'name': 'Foo Template'
'scopeName': 'text.html.foo.tpl'
'fileTypes': [
  'tpl'
]
'injections':
  'L:text.html.foo.tpl':
    'patterns': [
      {
        'include': 'text.html.mustache'
      }
    ]
'patterns': [
  {
    'include': 'text.html.basic'
  }
]
```

Thanks,
Caleb

**Comment by 50Wliu** [comment]
Ah.  I believe the problem is that `injections` aren't included when you include a grammar.  Let me think if there's a way around that.

**Comment by 50Wliu** [comment]
Does the following work?
```cson
'name': 'Foo Template'
'scopeName': 'text.html.foo.tpl'
'fileTypes': [
  'tpl'
]
'injections':
  'L:text.html.foo.tpl':
    'patterns': [
      {
        'include': 'text.html.mustache#comment'
      }
      {
        'include': 'text.html.mustache#block-expression-start'
      }
      {
        'include': 'text.html.mustache#block-expression-end'
      }
      {
        'include': 'text.html.mustache#escape'
      }
      {
        'include': 'text.html.mustache#template'
      }
    ]
'patterns': [
  {
    'include': 'text.html.basic'
  }
]
```

If it does, I can probably add a wrapper pattern around it so you only need to include one.

**Comment by caleb531** [comment]
@50Wliu Unfortunately, no. Same result as before—HTML highlighted, but Mustache/Handlebars tags are not.

![30617796-8ee22316-9d4c-11e7-9c1d-6a4d46381957](https://user-images.githubusercontent.com/872474/30716367-a2b7f482-9ece-11e7-82d5-8e2224731c74.png)

**Comment by caleb531** [comment]
@50Wliu EDIT: Never mind, it actually does work. Had to restart Atom. *facepalm*

**Comment by caleb531** [comment]
@50Wliu Good news! I was able to get syntax highlighting of Mustache/Handlebars tags working perfectly *and* consistently, using the following grammar:

```cson
'name': 'SCA Handlebars Template'
'scopeName': 'text.html.sca.tpl'
'fileTypes': [
  'tpl'
]
'patterns': [
  {
    'include': 'text.html.mustache'
  }
  {
    'include': 'text.html.mustache#comment'
  }
  {
    'include': 'text.html.mustache#block-expression-start'
  }
  {
    'include': 'text.html.mustache#block-expression-end'
  }
  {
    'include': 'text.html.mustache#escape'
  }
  {
    'include': 'text.html.mustache#template'
  }
]
```

I still look forward to that master pattern so I can simplify this a bit, but this ultimately solves my issue. Therefore, I am closing this issue.
