### ISSUE TITLE
Handlebars {{!-- style comments are not properly highlighted

### ISSUE THREAD

**Issue by baroquon** [atom/language-mustache#30]
### Description

In a handlebars file, if I start a `{{!--` style comment and the comment body contains closing brackets `}}` the syntax highlighting sees this as the end of the comment rather than the proper closing `--}}`. 

<img width="445" alt="screen shot 2017-10-13 at 12 16 20 pm" src="https://user-images.githubusercontent.com/4078/31557911-60a08a8e-b010-11e7-8337-4f8e81d74133.png">

[Handlebars Comments](http://handlebarsjs.com/#comments)

### Additional Information

Realizing this is specific to Handlebars rather than Mustache, would it be appropriate to include block level comment syntax rules here, or should Handlebars have it's own syntax highlighting independent of Mustache?

If you want this supported here, I would be happy to put together a PR.

**Comment by 50Wliu** [comment]
@baroquon Feel free to send a PR.

**Comment by baroquon** [comment]
Awesome, thanks. I hope to have a PR by Friday.
